Repository ChronoBank/ChronoMint, pull requests merged in 2018-02, with the labels that each got.

#593 Release 6.1.0 backport
  main.js
  packages/login-ui/components/LoginWithOptions/lang.js
  packages/login/network/ExchangeProvider.js
  packages/login/network/settings.js
  packages/login/redux/network/reducer.js
  src/components/assetsManager/HistoryTable/HistoryTable.jsx
  src/components/assetsManager/PlatformsList/PlatformsList.jsx
  src/components/common/TokenValue/TokenValue.js
  src/components/dialogs/ConfirmTxDialog/ConfirmTxDialog.js
  src/components/operations/Operations.jsx
  src/dao/AbstractContractDAO.js
  src/dao/AssetsManagerDAO.js
  src/dao/ERC20ManagerDAO.js
  src/i18n/en-notices.js
  src/i18n/en.js
  src/i18n/ru-notices.js
  src/i18n/ru.js
  src/layouts/Splash/Splash.js
  src/layouts/partials/RewardsContent/RewardsContent.jsx
  src/layouts/partials/RewardsContent/lang.js
  src/models/OperationModel.js
  src/models/notices/AssetsManagerNoticeModel.js
  src/redux/assetsManager/actions.js
  src/redux/settings/erc20/tokens/actions.js
  src/redux/voting/__snapshots__/reducer.spec.js.snap
  src/redux/voting/actions.js
  src/redux/voting/actions.spec.js
  src/redux/voting/reducer.spec.js
Labels: in progress

#596 MINT-1103 Implement ConfirmTx dialog for btc-like coins - Rebased
  packages/login/network/BitcoinEngine.js
  packages/login/network/BitcoinProvider.js
  src/components/common/GasSlider/GasSlider.jsx
  src/components/dialogs/ConfirmTransferDialog/ConfirmTransferDialog.js
  src/components/dialogs/ConfirmTransferDialog/ConfirmTransferDialog.scss
  src/dao/BitcoinDAO.js
  src/i18n/en-notices.js
  src/i18n/ru-notices.js
  src/models/TransferError.js
  src/models/TransferExecModel.js
  src/models/notices/TransferErrorNoticeModel.js
  src/models/notices/TransferNoticeModel.js
  src/redux/tokens/actions.js
  src/redux/tokens/selectors.js
  src/redux/ui/actions.js
  src/redux/wallet/selectors.js
  src/redux/watcher/actions.js
  src/services/TokenService.js
Labels: enhancement

#598 Added animation for ProfileSide panel & precision to TokenValue
  src/components/common/SideStack/SideStack.jsx
  src/components/common/TokenValue/TokenValue.js
  src/components/dashboard/Poll/Poll.jsx
  src/components/dialogs/PollDetailsDialog.jsx
  src/components/dialogs/VoteDialog.jsx
  src/layouts/partials/HeaderPartial/HeaderPartial.jsx
  src/layouts/partials/ProfileContent/ProfileContent.jsx
  src/layouts/partials/ProfileContent/ProfileContent.scss
  src/layouts/partials/SidePanel/SidePanel.jsx
  src/layouts/partials/index.js
  src/redux/sides/actions.js
  src/redux/sides/reducer.js
Labels: bug
